class Direction(object):
    def North(self):
        return "north"
    def South(self):
        return "south"
    def East(self):
        return "east"
    def West(self):
        return "west"
